"""create_coach_client_assignments_table

Revision ID: b04ba0191d08
Revises: 6cb039e9290f
Create Date: 2026-09-13 11:48:20.771956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04ba0191d08'
down_revision: Union[str, None] = '6cb039e9290f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_client_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_client_assignments_client_id'), 'coach_client_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_coach_id'), 'coach_client_assignments', ['coach_id'], unique=False)
    op.create_index(op.f('ix_coach_client_assignments_tenant_id'), 'coach_client_assignments', ['tenant_id'], unique=False)
    op.create_index('uq_active_coach_client_assignment', 'coach_client_assignments', ['coach_id', 'client_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_coach_client_assignment', table_name='coach_client_assignments', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_coach_client_assignments_tenant_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_coach_id'), table_name='coach_client_assignments')
    op.drop_index(op.f('ix_coach_client_assignments_client_id'), table_name='coach_client_assignments')
    op.drop_table('coach_client_assignments')
    # ### end Alembic commands ###
