"""create_exercises_and_video_library

Revision ID: 3819e36dc9f4
Revises: b53e59a180b9
Create Date: 2026-09-16 09:24:45.012888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3819e36dc9f4'
down_revision: Union[str, None] = 'b53e59a180b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('muscle_group', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscle_group', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_difficulty'), 'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_exercise_type'), 'exercises', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercises_is_active'), 'exercises', ['is_active'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group'), 'exercises', ['muscle_group'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index('ix_exercises_tenant_active', 'exercises', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_exercises_tenant_id'), 'exercises', ['tenant_id'], unique=False)
    op.create_table('exercise_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_videos_exercise_id'), 'exercise_videos', ['exercise_id'], unique=False)
    op.create_index('ix_exercise_videos_exercise_primary', 'exercise_videos', ['exercise_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_exercise_videos_is_primary'), 'exercise_videos', ['is_primary'], unique=False)
    op.add_column('workout_exercises', sa.Column('exercise_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_workout_exercises_exercise_id'), 'workout_exercises', ['exercise_id'], unique=False)
    op.create_foreign_key(None, 'workout_exercises', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_exercises', type_='foreignkey')
    op.drop_index(op.f('ix_workout_exercises_exercise_id'), table_name='workout_exercises')
    op.drop_column('workout_exercises', 'exercise_id')
    op.drop_index(op.f('ix_exercise_videos_is_primary'), table_name='exercise_videos')
    op.drop_index('ix_exercise_videos_exercise_primary', table_name='exercise_videos')
    op.drop_index(op.f('ix_exercise_videos_exercise_id'), table_name='exercise_videos')
    op.drop_table('exercise_videos')
    op.drop_index(op.f('ix_exercises_tenant_id'), table_name='exercises')
    op.drop_index('ix_exercises_tenant_active', table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_muscle_group'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_is_active'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_exercise_type'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
