"""create_training_sessions_table

Revision ID: a95bcca909db
Revises: 1edced19b231
Create Date: 2026-09-15 10:03:07.279376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95bcca909db'
down_revision: Union[str, None] = '1edced19b231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('training_plan_id', sa.String(length=36), nullable=True),
    sa.Column('workout_day_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_days.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_client_id'), 'training_sessions', ['client_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_coach_id'), 'training_sessions', ['coach_id'], unique=False)
    op.create_index('ix_training_sessions_coach_start', 'training_sessions', ['coach_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_training_sessions_scheduled_start'), 'training_sessions', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_training_sessions_status'), 'training_sessions', ['status'], unique=False)
    op.create_index('ix_training_sessions_tenant_client', 'training_sessions', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_training_sessions_tenant_coach', 'training_sessions', ['tenant_id', 'coach_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_tenant_id'), 'training_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_training_plan_id'), 'training_sessions', ['training_plan_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_workout_day_id'), 'training_sessions', ['workout_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sessions_workout_day_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_training_plan_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_tenant_id'), table_name='training_sessions')
    op.drop_index('ix_training_sessions_tenant_coach', table_name='training_sessions')
    op.drop_index('ix_training_sessions_tenant_client', table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_status'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_scheduled_start'), table_name='training_sessions')
    op.drop_index('ix_training_sessions_coach_start', table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_coach_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_client_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
