"""create_training_plans_and_workouts_tables

Revision ID: 1edced19b231
Revises: b04ba0191d08
Create Date: 2026-09-14 12:28:18.183317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edced19b231'
down_revision: Union[str, None] = 'b04ba0191d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_client_id'), 'training_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_training_plans_coach_id'), 'training_plans', ['coach_id'], unique=False)
    op.create_index(op.f('ix_training_plans_status'), 'training_plans', ['status'], unique=False)
    op.create_index('ix_training_plans_tenant_client', 'training_plans', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_training_plans_tenant_coach', 'training_plans', ['tenant_id', 'coach_id'], unique=False)
    op.create_index(op.f('ix_training_plans_tenant_id'), 'training_plans', ['tenant_id'], unique=False)
    op.create_table('workout_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('training_plan_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_days_plan_order', 'workout_days', ['training_plan_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_workout_days_tenant_id'), 'workout_days', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workout_days_training_plan_id'), 'workout_days', ['training_plan_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_day_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_day_id'], ['workout_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_exercises_day_order', 'workout_exercises', ['workout_day_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_workout_exercises_tenant_id'), 'workout_exercises', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workout_exercises_workout_day_id'), 'workout_exercises', ['workout_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercises_workout_day_id'), table_name='workout_exercises')
    op.drop_index(op.f('ix_workout_exercises_tenant_id'), table_name='workout_exercises')
    op.drop_index('ix_workout_exercises_day_order', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_workout_days_training_plan_id'), table_name='workout_days')
    op.drop_index(op.f('ix_workout_days_tenant_id'), table_name='workout_days')
    op.drop_index('ix_workout_days_plan_order', table_name='workout_days')
    op.drop_table('workout_days')
    op.drop_index(op.f('ix_training_plans_tenant_id'), table_name='training_plans')
    op.drop_index('ix_training_plans_tenant_coach', table_name='training_plans')
    op.drop_index('ix_training_plans_tenant_client', table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_status'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_coach_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_client_id'), table_name='training_plans')
    op.drop_table('training_plans')
    # ### end Alembic commands ###
