"""create_progress_records_table

Revision ID: b53e59a180b9
Revises: a95bcca909db
Create Date: 2026-09-15 10:38:20.673716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53e59a180b9'
down_revision: Union[str, None] = 'a95bcca909db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('coach_id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arm_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thigh_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('training_session_id', sa.String(length=36), nullable=True),
    sa.Column('training_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_client_id'), 'progress_records', ['client_id'], unique=False)
    op.create_index('ix_progress_records_client_recorded_at', 'progress_records', ['client_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_progress_records_coach_id'), 'progress_records', ['coach_id'], unique=False)
    op.create_index(op.f('ix_progress_records_recorded_at'), 'progress_records', ['recorded_at'], unique=False)
    op.create_index('ix_progress_records_tenant_client', 'progress_records', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_progress_records_tenant_coach', 'progress_records', ['tenant_id', 'coach_id'], unique=False)
    op.create_index(op.f('ix_progress_records_tenant_id'), 'progress_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_progress_records_training_plan_id'), 'progress_records', ['training_plan_id'], unique=False)
    op.create_index(op.f('ix_progress_records_training_session_id'), 'progress_records', ['training_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_records_training_session_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_training_plan_id'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_tenant_id'), table_name='progress_records')
    op.drop_index('ix_progress_records_tenant_coach', table_name='progress_records')
    op.drop_index('ix_progress_records_tenant_client', table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_recorded_at'), table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_coach_id'), table_name='progress_records')
    op.drop_index('ix_progress_records_client_recorded_at', table_name='progress_records')
    op.drop_index(op.f('ix_progress_records_client_id'), table_name='progress_records')
    op.drop_table('progress_records')
    # ### end Alembic commands ###
